-- Generated by tools/generate-recipes.py from GT5-Unofficial 5.09.54.133, NewHorizonsCoreMod 2.9.61
return {
  {
    output = {name = "plasma.advancednitinol", label = "Advanced Nitinol Plasma", amount = 1000},
    inputs = {{name = "plasma.xenon", label = "Xenon Plasma", amount = 144}, {name = "plasma.runite", label = "Runite Plasma", amount = 1000}},
    startupEu = 500000000, eut = 491520, duration = 16
  },
  {
    output = {name = "plasma.americium", label = "Americium Plasma", amount = 144},
    inputs = {{name = "molten.plutonium241", label = "Molten Plutonium 241", amount = 144}, {name = "hydrogen", label = "Hydrogen", amount = 2000}},
    startupEu = 500000000, eut = 98304, duration = 64
  },
  {
    output = {name = "plasma.astraltitanium", label = "Astral Titanium Plasma", amount = 1000},
    inputs = {{name = "plasma.krypton", label = "Krypton Plasma", amount = 144}, {name = "plasma.force", label = "Force Plasma", amount = 1000}},
    startupEu = 300000000, eut = 122880, duration = 32
  },
  {
    output = {name = "plasma.bismuth", label = "Bismuth Plasma", amount = 144},
    inputs = {{name = "molten.tantalum", label = "Molten Tantalum", amount = 144}, {name = "plasma.zinc", label = "Zinc Plasma", amount = 72}},
    startupEu = 350000000, eut = 98304, duration = 16
  },
  {
    output = {name = "plasma.boron", label = "Boron Plasma", amount = 144},
    inputs = {{name = "plasma.helium", label = "Helium Plasma", amount = 144}, {name = "molten.lithium", label = "Molten Lithium", amount = 144}},
    startupEu = 50000000, eut = 10240, duration = 240
  },
  {
    output = {name = "plasma.bromine", label = "Bromine Plasma", amount = 144},
    inputs = {{name = "molten.manganese", label = "Molten Manganese", amount = 144}, {name = "neon", label = "Neon", amount = 500}},
    startupEu = 1000000000, eut = 196608, duration = 32
  },
  {
    output = {name = "plasma.calcium", label = "Calcium Plasma", amount = 16},
    inputs = {{name = "molten.magnesium", label = "Molten Magnesium", amount = 128}, {name = "oxygen", label = "Oxygen", amount = 128}},
    startupEu = 120000000, eut = 7680, duration = 128
  },
  {
    output = {name = "plasma.celestialtungsten", label = "Celestial Tungsten Plasma", amount = 1000},
    inputs = {{name = "plasma.advancednitinol", label = "Advanced Nitinol Plasma", amount = 72}, {name = "molten.tartarite", label = "Molten Tartarite", amount = 2}},
    startupEu = 500000000, eut = 491520, duration = 8
  },
  {
    output = {name = "plasma.fermium", label = "Fermium Plasma", amount = 100},
    inputs = {{name = "plasma.americium", label = "Americium Plasma", amount = 100}, {name = "plasma.boron", label = "Boron Plasma", amount = 100}},
    startupEu = 1000000000, eut = 1966080, duration = 600
  },
  {
    output = {name = "plasma.fermium", label = "Fermium Plasma", amount = 576},
    inputs = {{name = "plasma.force", label = "Force Plasma", amount = 576}, {name = "molten.rubidium", label = "Molten Rubidium", amount = 576}},
    startupEu = 6000000000, eut = 7864320, duration = 32
  },
  {
    output = {name = "plasma.force", label = "Force Plasma", amount = 1000},
    inputs = {{name = "plasma.neon", label = "Neon Plasma", amount = 144}, {name = "molten.arcanite", label = "Molten Arcanite", amount = 2}},
    startupEu = 100000000, eut = 30720, duration = 32
  },
  {
    output = {name = "plasma.helium", label = "Helium Plasma", amount = 125},
    inputs = {{name = "deuterium", label = "Deuterium", amount = 125}, {name = "tritium", label = "Tritium", amount = 125}},
    startupEu = 40000000, eut = 3840, duration = 16
  },
  {
    output = {name = "plasma.helium", label = "Helium Plasma", amount = 125},
    inputs = {{name = "deuterium", label = "Deuterium", amount = 125}, {name = "helium-3", label = "Helium-3", amount = 125}},
    startupEu = 60000000, eut = 1920, duration = 16
  },
  {
    output = {name = "plasma.iron", label = "Iron Plasma", amount = 144},
    inputs = {{name = "molten.silicon", label = "Molten Raw Silicon", amount = 16}, {name = "molten.magnesium", label = "Molten Magnesium", amount = 16}},
    startupEu = 360000000, eut = 7680, duration = 32
  },
  {
    output = {name = "plasma.krypton", label = "Krypton Plasma", amount = 144},
    inputs = {{name = "plasma.niobium", label = "Niobium Plasma", amount = 144}, {name = "plasma.zinc", label = "Zinc Plasma", amount = 144}},
    startupEu = 300000000, eut = 122880, duration = 32
  },
  {
    output = {name = "plasma.lead", label = "Lead Plasma", amount = 576},
    inputs = {{name = "molten.tellurium", label = "Molten Tellurium", amount = 576}, {name = "molten.zinc", label = "Molten Zinc", amount = 576}},
    startupEu = 6000000000, eut = 3932160, duration = 4
  },
  {
    output = {name = "molten.americium", label = "Molten Americium", amount = 16},
    inputs = {{name = "molten.lutetium", label = "Molten Lutetium", amount = 16}, {name = "molten.chrome", label = "Molten Chrome", amount = 16}},
    startupEu = 200000000, eut = 49152, duration = 96
  },
  {
    output = {name = "molten.americium", label = "Molten Americium", amount = 32},
    inputs = {{name = "molten.lutetium", label = "Molten Lutetium", amount = 32}, {name = "molten.promethium", label = "Molten Promethium", amount = 16}},
    startupEu = 200000000, eut = 38764, duration = 24
  },
  {
    output = {name = "molten.californium", label = "Molten Californium", amount = 48},
    inputs = {{name = "molten.plutonium", label = "Molten Plutonium 239", amount = 48}, {name = "molten.beryllium", label = "Molten Beryllium", amount = 48}},
    startupEu = 480000000, eut = 49152, duration = 240
  },
  {
    output = {name = "molten.californium", label = "Molten Californium", amount = 144},
    inputs = {{name = "molten.curium", label = "Molten Curium", amount = 144}, {name = "plasma.helium", label = "Helium Plasma", amount = 144}},
    startupEu = 750000000, eut = 196608, duration = 32
  },
  {
    output = {name = "molten.chrome", label = "Molten Chrome", amount = 16},
    inputs = {{name = "molten.vanadium", label = "Molten Vanadium", amount = 16}, {name = "hydrogen", label = "Hydrogen", amount = 125}},
    startupEu = 140000000, eut = 24576, duration = 64
  },
  {
    output = {name = "molten.curium", label = "Molten Curium", amount = 144},
    inputs = {{name = "molten.plutonium241", label = "Molten Plutonium 241", amount = 144}, {name = "helium", label = "Helium", amount = 1000}},
    startupEu = 500000000, eut = 98304, duration = 96
  },
  {
    output = {name = "molten.duranium", label = "Molten Duranium", amount = 16},
    inputs = {{name = "molten.gallium", label = "Molten Gallium", amount = 16}, {name = "radon", label = "Radon", amount = 125}},
    startupEu = 140000000, eut = 15360, duration = 64
  },
  {
    output = {name = "molten.europium", label = "Molten Europium", amount = 16},
    inputs = {{name = "molten.neodymium", label = "Molten Neodymium", amount = 16}, {name = "hydrogen", label = "Hydrogen", amount = 48}},
    startupEu = 150000000, eut = 24576, duration = 32
  },
  {
    output = {name = "molten.europium", label = "Molten Europium", amount = 32},
    inputs = {{name = "molten.neodymium", label = "Molten Neodymium", amount = 32}, {name = "molten.promethium", label = "Molten Promethium", amount = 16}},
    startupEu = 150000000, eut = 24576, duration = 8
  },
  {
    output = {name = "molten.flerovium_gt5u", label = "Molten Flerovium", amount = 144},
    inputs = {{name = "molten.plutonium241", label = "Molten Plutonium 241", amount = 144}, {name = "plasma.calcium", label = "Calcium Plasma", amount = 144}},
    startupEu = 1000000000, eut = 196608, duration = 160
  },
  {
    output = {name = "molten.hypogen", label = "Molten Hypogen", amount = 36},
    inputs = {{name = "molten.dragonblood", label = "Molten Dragonblood", amount = 144}, {name = "molten.rhugnor", label = "Molten Rhugnor", amount = 288}},
    startupEu = 1200000000, eut = 1966080, duration = 8192
  },
  {
    output = {name = "molten.indium", label = "Molten Indium", amount = 16},
    inputs = {{name = "molten.silver", label = "Molten Silver", amount = 16}, {name = "molten.lithium", label = "Molten Lithium", amount = 16}},
    startupEu = 380000000, eut = 24576, duration = 32
  },
  {
    output = {name = "molten.iridium", label = "Molten Iridium", amount = 16},
    inputs = {{name = "molten.lithium", label = "Molten Lithium", amount = 16}, {name = "molten.tungsten", label = "Molten Tungsten", amount = 16}},
    startupEu = 300000000, eut = 30720, duration = 64
  },
  {
    output = {name = "molten.iron", label = "Molten Iron", amount = 16},
    inputs = {{name = "molten.manganese", label = "Molten Manganese", amount = 16}, {name = "hydrogen", label = "Hydrogen", amount = 16}},
    startupEu = 120000000, eut = 7680, duration = 64
  },
  {
    output = {name = "molten.metastable oganesson", label = "Molten Metastable Oganesson", amount = 36},
    inputs = {{name = "molten.enriched naquadah alloy", label = "Molten Enriched Naquadah Alloy", amount = 144}, {name = "oganesson", label = "Oganesson", amount = 250}},
    startupEu = 1000000000, eut = 491520, duration = 600
  },
  {
    output = {name = "molten.metastable oganesson", label = "Molten Metastable Oganesson", amount = 576},
    inputs = {{name = "plasma.copper", label = "Copper Plasma", amount = 576}, {name = "oganesson", label = "Oganesson", amount = 1000}},
    startupEu = 6000000000, eut = 7864320, duration = 100
  },
  {
    output = {name = "molten.naquadah", label = "Molten Naquadah", amount = 16},
    inputs = {{name = "molten.plutonium", label = "Molten Plutonium 239", amount = 16}, {name = "molten.thorium", label = "Molten Thorium", amount = 16}},
    startupEu = 300000000, eut = 30720, duration = 64
  },
  {
    output = {name = "molten.neutronium", label = "Molten Neutronium", amount = 144},
    inputs = {{name = "molten.americium", label = "Molten Americium", amount = 144}, {name = "molten.naquadria", label = "Molten Naquadria", amount = 144}},
    startupEu = 600000000, eut = 122880, duration = 240
  },
  {
    output = {name = "molten.osmium", label = "Molten Osmium", amount = 16},
    inputs = {{name = "molten.tungsten", label = "Molten Tungsten", amount = 16}, {name = "helium", label = "Helium", amount = 16}},
    startupEu = 150000000, eut = 24578, duration = 256
  },
  {
    output = {name = "molten.platinum", label = "Molten Platinum", amount = 16},
    inputs = {{name = "molten.beryllium", label = "Molten Beryllium", amount = 16}, {name = "molten.tungsten", label = "Molten Tungsten", amount = 16}},
    startupEu = 150000000, eut = 30720, duration = 32
  },
  {
    output = {name = "molten.plutonium", label = "Molten Plutonium 239", amount = 16},
    inputs = {{name = "molten.uranium", label = "Molten Uranium 238", amount = 16}, {name = "helium", label = "Helium", amount = 16}},
    startupEu = 480000000, eut = 49152, duration = 128
  },
  {
    output = {name = "molten.rhugnor", label = "Molten Rhugnor", amount = 144},
    inputs = {{name = "molten.infinity", label = "Molten Infinity", amount = 144}, {name = "molten.quantum", label = "Molten Quantum", amount = 288}},
    startupEu = 2000000000, eut = 491520, duration = 512
  },
  {
    output = {name = "molten.rhugnor", label = "Molten Rhugnor", amount = 576},
    inputs = {{name = "quarkgluonplasma", label = "Degenerate Quark Gluon Plasma", amount = 72}, {name = "molten.quantum", label = "Molten Quantum", amount = 576}},
    startupEu = 2000000000, eut = 7864320, duration = 50
  },
  {
    output = {name = "molten.rubidium", label = "Molten Rubidium", amount = 144},
    inputs = {{name = "molten.cobalt", label = "Molten Cobalt", amount = 144}, {name = "neon", label = "Neon", amount = 144}},
    startupEu = 500000000, eut = 98304, duration = 24
  },
  {
    output = {name = "molten.sunnarium", label = "Molten Sunnarium", amount = 16},
    inputs = {{name = "molten.glowstone", label = "Molten Glowstone", amount = 16}, {name = "plasma.helium", label = "Helium Plasma", amount = 4}},
    startupEu = 40000000, eut = 7680, duration = 32
  },
  {
    output = {name = "molten.tritanium", label = "Molten Tritanium", amount = 16},
    inputs = {{name = "molten.titanium", label = "Molten Titanium", amount = 48}, {name = "molten.duranium", label = "Molten Duranium", amount = 32}},
    startupEu = 200000000, eut = 30720, duration = 64
  },
  {
    output = {name = "molten.tungsten", label = "Molten Tungsten", amount = 16},
    inputs = {{name = "molten.tantalum", label = "Molten Tantalum", amount = 16}, {name = "tritium", label = "Tritium", amount = 16}},
    startupEu = 200000000, eut = 24576, duration = 16
  },
  {
    output = {name = "molten.uranium", label = "Molten Uranium 238", amount = 16},
    inputs = {{name = "mercury", label = "Mercury", amount = 16}, {name = "molten.magnesium", label = "Molten Magnesium", amount = 16}},
    startupEu = 240000000, eut = 49152, duration = 64
  },
  {
    output = {name = "molten.uranium", label = "Molten Uranium 238", amount = 16},
    inputs = {{name = "molten.gold", label = "Molten Gold", amount = 16}, {name = "molten.aluminium", label = "Molten Aluminium", amount = 16}},
    startupEu = 240000000, eut = 49152, duration = 64
  },
  {
    output = {name = "naquadah based liquid fuel mki", label = "Naquadah Based Liquid Fuel MkI", amount = 100},
    inputs = {{name = "light naquadah fuel", label = "Light Naquadah Fuel", amount = 780}, {name = "heavy naquadah fuel", label = "Heavy Naquadah Fuel", amount = 360}},
    startupEu = 320000000, eut = 30720, duration = 500
  },
  {
    output = {name = "plasma.neon", label = "Neon Plasma", amount = 1000},
    inputs = {{name = "plasma.boron", label = "Boron Plasma", amount = 144}, {name = "plasma.calcium", label = "Calcium Plasma", amount = 16}},
    startupEu = 100000000, eut = 30720, duration = 64
  },
  {
    output = {name = "plasma.neptunium", label = "Neptunium Plasma", amount = 100},
    inputs = {{name = "plasma.radon", label = "Radon Plasma", amount = 100}, {name = "plasma.nitrogen", label = "Nitrogen Plasma", amount = 100}},
    startupEu = 1000000000, eut = 1966080, duration = 600
  },
  {
    output = {name = "plasma.neptunium", label = "Neptunium Plasma", amount = 576},
    inputs = {{name = "plasma.xenon", label = "Xenon Plasma", amount = 576}, {name = "molten.yttrium", label = "Molten Yttrium", amount = 576}},
    startupEu = 6000000000, eut = 7864320, duration = 32
  },
  {
    output = {name = "plasma.nickel", label = "Nickel Plasma", amount = 144},
    inputs = {{name = "molten.potassium", label = "Molten Potassium", amount = 16}, {name = "fluorine", label = "Fluorine", amount = 144}},
    startupEu = 480000000, eut = 30720, duration = 16
  },
  {
    output = {name = "plasma.niobium", label = "Niobium Plasma", amount = 144},
    inputs = {{name = "molten.cobalt", label = "Molten Cobalt", amount = 144}, {name = "molten.silicon", label = "Molten Raw Silicon", amount = 144}},
    startupEu = 200000000, eut = 49152, duration = 16
  },
  {
    output = {name = "plasma.nitrogen", label = "Nitrogen Plasma", amount = 125},
    inputs = {{name = "molten.beryllium", label = "Molten Beryllium", amount = 16}, {name = "deuterium", label = "Deuterium", amount = 375}},
    startupEu = 180000000, eut = 15360, duration = 16
  },
  {
    output = {name = "oganesson", label = "Oganesson", amount = 720},
    inputs = {{name = "molten.californium", label = "Molten Californium", amount = 32}, {name = "molten.calcium", label = "Molten Calcium", amount = 720}},
    startupEu = 600000000, eut = 49152, duration = 480
  },
  {
    output = {name = "plasma.oxygen", label = "Oxygen Plasma", amount = 144},
    inputs = {{name = "plasma.boron", label = "Boron Plasma", amount = 144}, {name = "molten.lithium", label = "Molten Lithium", amount = 144}},
    startupEu = 180000000, eut = 49152, duration = 240
  },
  {
    output = {name = "plasma.plutonium241", label = "Plutonium 241 Plasma", amount = 576},
    inputs = {{name = "molten.lutetium", label = "Molten Lutetium", amount = 576}, {name = "molten.vanadium", label = "Molten Vanadium", amount = 576}},
    startupEu = 6000000000, eut = 3932160, duration = 4
  },
  {
    output = {name = "plutonium based liquid fuel (excited state)", label = "Plutonium Based Liquid Fuel (Excited State)", amount = 20},
    inputs = {{name = "molten.lutetium", label = "Molten Lutetium", amount = 16}, {name = "plutonium based liquid fuel", label = "Plutonium Based Liquid Fuel", amount = 20}},
    startupEu = 220000000, eut = 15360, duration = 20
  },
  {
    output = {name = "plasma.radon", label = "Radon Plasma", amount = 144},
    inputs = {{name = "molten.iridium", label = "Molten Iridium", amount = 144}, {name = "fluorine", label = "Fluorine", amount = 500}},
    startupEu = 450000000, eut = 98304, duration = 32
  },
  {
    output = {name = "plasma.runite", label = "Runite Plasma", amount = 1000},
    inputs = {{name = "plasma.astraltitanium", label = "Astral Titanium Plasma", amount = 144}, {name = "molten.titansteel", label = "Molten Titansteel", amount = 2}},
    startupEu = 300000000, eut = 122880, duration = 32
  },
  {
    output = {name = "plasma.silver", label = "Silver Plasma", amount = 144},
    inputs = {{name = "molten.gold", label = "Molten Gold", amount = 144}, {name = "molten.arsenic", label = "Molten Arsenic", amount = 144}},
    startupEu = 350000000, eut = 49152, duration = 16
  },
  {
    output = {name = "plasma.sulfur", label = "Sulfur Plasma", amount = 144},
    inputs = {{name = "molten.aluminium", label = "Molten Aluminium", amount = 16}, {name = "molten.lithium", label = "Molten Lithium", amount = 16}},
    startupEu = 240000000, eut = 10240, duration = 32
  },
  {
    output = {name = "plasma.technetium", label = "Technetium Plasma", amount = 288},
    inputs = {{name = "fluorine", label = "Fluorine", amount = 1000}, {name = "molten.selenium", label = "Molten Selenium", amount = 144}},
    startupEu = 800000000, eut = 196608, duration = 64
  },
  {
    output = {name = "plasma.thorium", label = "Thorium Plasma", amount = 576},
    inputs = {{name = "molten.osmium", label = "Molten Osmium", amount = 576}, {name = "molten.silicon", label = "Molten Raw Silicon", amount = 576}},
    startupEu = 6000000000, eut = 3932160, duration = 4
  },
  {
    output = {name = "plasma.tin", label = "Tin Plasma", amount = 288},
    inputs = {{name = "molten.silver", label = "Molten Silver", amount = 144}, {name = "helium-3", label = "Helium-3", amount = 375}},
    startupEu = 280000000, eut = 49152, duration = 16
  },
  {
    output = {name = "plasma.titanium", label = "Titanium Plasma", amount = 144},
    inputs = {{name = "molten.aluminium", label = "Molten Aluminium", amount = 144}, {name = "fluorine", label = "Fluorine", amount = 144}},
    startupEu = 180000000, eut = 49152, duration = 160
  },
  {
    output = {name = "unformed hexanite", label = "Unformed Hexanite", amount = 576},
    inputs = {{name = "plasma.redstone", label = "Redstone Plasma", amount = 576}, {name = "molten.ichorium", label = "Molten Ichorium", amount = 576}},
    startupEu = 6000000000, eut = 3932160, duration = 32
  },
  {
    output = {name = "uranium based liquid fuel (excited state)", label = "Uranium Based Liquid Fuel (Excited State)", amount = 10},
    inputs = {{name = "uranium based liquid fuel", label = "Uranium Based Liquid Fuel", amount = 10}, {name = "hydrogen", label = "Hydrogen", amount = 100}},
    startupEu = 200000000, eut = 7680, duration = 40
  },
  {
    output = {name = "plasma.xenon", label = "Xenon Plasma", amount = 144},
    inputs = {{name = "molten.curium", label = "Molten Curium", amount = 144}, {name = "plasma.americium", label = "Americium Plasma", amount = 144}},
    startupEu = 500000000, eut = 491520, duration = 16
  },
  {
    output = {name = "plasma.zinc", label = "Zinc Plasma", amount = 72},
    inputs = {{name = "molten.copper", label = "Molten Copper", amount = 72}, {name = "tritium", label = "Tritium", amount = 250}},
    startupEu = 180000000, eut = 49152, duration = 16
  }
}
