name: Release Production

on:
  push:
    tags-ignore:
      - "dev-*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create tar archive
      run: |
        tar -cvf FusionMaintainer.tar --exclude-from=.tarignore *

    - name: Create Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${{ github.ref_name }}" FusionMaintainer.tar --title "Release ${{ github.ref_name }}"
